language: cpp
matrix:  
  include:
    - os: linux
      sudo: required
      dist: bionic
      compiler:
        - gcc

      cache: ccache
      before_script:
        - >
          sudo apt-get install default-jdk default-jdk-headless default-jre default-jre-headless 
          python2.7-dev libpython2.7-dev libssl1.0.0 zlib1g zlib1g-dev libssl-dev libusb-1.0-0 
          libusb-1.0-0-dev libdbus-1-3 libdbus-1-dev libbluetooth3 libbluetooth-dev zlib1g zlib1g-dev 
          python-numpy python-setuptools python-wheel git cmake-qt-gui g++ make libboost-all-dev autoconf 
          automake libtool bison libpcre3-dev python3-dev python3-numpy python3-setuptools python3-wheel
          mono-devel -qq
        - | 
            (
            rm -rf swig_build_dir
            mkdir -p swig_build_dir
            cd swig_build_dir
            curl -L https://sourceforge.net/projects/swig/files/swig/swig-4.0.0-beta1/swig-4.0.0-beta1.tar.gz --output swig-4.0.0-beta1.tar.gz
            tar xf swig-4.0.0-beta1.tar.gz
            cd swig-4.0.0-beta1            
            ./configure
            make
            sudo make install
            )
      env:
        - >
          RR_CMAKE_EXTRA_ARGS="-DBUILD_PYTHON=ON -DCMAKE_BUILD_TYPE=Release -DPACKAGE_SWIG_SOURCE_ALL=ON"
        - RR_CMAKE_GENERATOR="Unix Makefiles"
        
    
script:
  - mkdir -p build2
  - cd build2
  - cmake -G "$RR_CMAKE_GENERATOR" $RR_CMAKE_EXTRA_ARGS ..
  - cmake --build . --config Release --target package_source_swig
  - cmake --build . --config Release --target package_source
  - mv generated_src out/ || true
  - cp *.tar.gz out/ || true
  - cp *.zip out/ || true
  - export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
  - export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - tar czf out.tar.gz build2
  - mv out.tar.gz build2/

deploy:
  provider: releases
  repo: johnwason/robotraconteur_travisci_deploy
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  deployment_file: true
  file: $TRAVIS_BUILD_DIR/build2/out.tar.gz
  verbose: true
  draft: false
  name: travisci build ${TRAVIS_REPO_SLUG} ${TRAVIS_JOB_NUMBER} 
  body: |
    repo: ${TRAVIS_REPO_SLUG}
    branch: ${TRAVIS_BRANCH}
    job: ${TRAVIS_JOB_NUMBER}
    buildid: ${TRAVIS_BUILD_ID}
    buildurl: ${TRAVIS_JOB_WEB_URL}
    commit: ${TRAVIS_COMMIT}
    tag: ${TRAVIS_TAG}
    osname: ${TRAVIS_OS_NAME}
    cmakegenerator: ${RR_CMAKE_GENERATOR}
  on:
    all_branches: true    
    condition: $TRAVIS_BRANCH =~ ^(master|travisci2)$
    condition: $TRAVIS_REPO_OWNER =~ ^(robotraconteur|johnwason)$
    condition: "$TRAVIS_REPO_NAME = robotraconteur"
    
    
