name: Dist Test

on: 
  workflow_dispatch:
    inputs:
      ref:
        description: 'git ref to run against'
        required: true

jobs:
  build-ubuntu:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: '${{ github.event.inputs.ref }}'
        repository: robotraconteur/robotraconteur
    - name: add PPA
      run: sudo add-apt-repository ppa:robotraconteur/ppa -y     
    - name: apt update
      run: sudo apt update
    - name: apt
      run: >
        sudo apt-get install robotraconteur-dev python3-robotraconteur libboost-all-dev libbluetooth-dev
        libdbus-1-dev libssl-dev libusb-1.0-0-dev  -q 
    - name: apt python2
      if: matrix.os != 'ubuntu-20.04'
      run: >
        sudo apt-get install python-robotraconteur -q
    - name: configure
      run: >
        mkdir build && cd build &&
        cmake -G "Unix Makefiles" -DBUILD_CORE=OFF -DBUILD_TEST=ON -DBUILD_TESTING=ON
        ..
    - name: build
      run: |        
        cd build
        cmake --build . --config Release -j 4
    - name: test cpp
      run: |
        cd build
        ctest . -C Release --output-on-failure
    - name: test python
      if: matrix.os != 'ubuntu-20.04'
      env:
        ROBOTRACONTEUR_ROBDEF_PATH: '${{ github.workspace }}/testing/RobotRaconteurTest'
      run: |
        cd RobotRaconteurPython/test
        python RobotRaconteurPythonTest.py loopback
    - name: test python3
      if: matrix.os == 'false'
      env:
        ROBOTRACONTEUR_ROBDEF_PATH: '${{ github.workspace }}/testing/RobotRaconteurTest'
      run: |
        cd RobotRaconteurPython/test
        python3 RobotRaconteurPythonTest.py loopback

        
      