name: Ubuntu CI

on:
  push:
  pull_request:

jobs:
  build-ubuntu-20:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: >
        sudo apt-get install default-jdk default-jdk-headless default-jre default-jre-headless 
        libssl1.0.0 zlib1g zlib1g-dev libssl-dev libusb-1.0-0 
        libusb-1.0-0-dev libdbus-1-3 libdbus-1-dev libbluetooth3 libbluetooth-dev zlib1g zlib1g-dev 
        git cmake-qt-gui g++ make libboost-all-dev autoconf 
        automake libtool bison libpcre3-dev python3-dev python3-numpy python3-setuptools python3-wheel 
        mono-devel swig
    - name: configure
      run:
        cd .. 
        mkdir build2 && cd build2 
        cmake -G "$RR_CMAKE_GENERATOR" -DBUILD_GEN=ON  -DBUILD_TEST=ON -DBUILD_PYTHON3=ON -DBUILD_PYTHON3_WHEEL=ON \
        -DBoost_USE_STATIC_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DPYTHON3_EXECUTABLE=/usr/bin/python3 
        -DBUILD_JAVA=ON -DBUILD_NET=ON -DPACKAGE_SWIG_SOURCE_ALL=ON \
        -DJAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 \
        ../robotraconteur
    - name: build
      run: |
        cd ../build2
        cmake --build . --config Release
    - name: build source
      run: |
        cd ../build2
        cmake --build . --config Release --target package_source || true
        mv generated_src out/
        cp ../robotraconteur/LICENSE.txt out/
    - name: archive out
      uses: actions/upload-artifact@v2
      with:
        name: out
        path: ../build2/out