name: Ubuntu CI

on:
  push:
  pull_request:

jobs:
  build-ubuntu:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: >
        sudo apt-get install default-jdk default-jdk-headless default-jre default-jre-headless 
        zlib1g zlib1g-dev libssl-dev libusb-1.0-0 python-dev python-numpy python-setuptools 
        libusb-1.0-0-dev libdbus-1-3 libdbus-1-dev libbluetooth3 libbluetooth-dev zlib1g zlib1g-dev 
        git cmake-qt-gui g++ make libboost-all-dev autoconf 
        automake libtool bison libpcre3-dev python3-dev python3-numpy python3-setuptools python3-wheel 
        mono-devel -q
    - name: apt-swig
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt-get install swig
    - name: build-swig
      if: matrix.os != 'ubuntu-20.04'
      run: |
        cd ..
        rm -rf swig_build_dir
        mkdir -p swig_build_dir
        cd swig_build_dir
        curl -L http://prdownloads.sourceforge.net/swig/swig-4.0.1.tar.gz --output swig-4.0.1.tar.gz
        tar xf swig-4.0.1.tar.gz
        cd swig-4.0.1
        ./configure
        make
        sudo make install
    - name: configure
      run: >
        cd .. &&
        mkdir build2 && cd build2 &&
        cmake -G "Unix Makefiles" -DBUILD_GEN=ON  -DBUILD_TEST=ON -DBUILD_PYTHON3=ON -DBUILD_PYTHON3_WHEEL=ON 
        -DBoost_USE_STATIC_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DPYTHON3_EXECUTABLE=/usr/bin/python3 
        -DBUILD_JAVA=ON -DBUILD_NET=ON -DPACKAGE_SWIG_SOURCE_ALL=ON -DJAVA_HOME=/usr/lib/jvm/default-java 
        -DBUILD_PYTHON=ON -DBUILD_PYTHON_WHEEL=OFF
        ../robotraconteur
    - name: build
      run: |        
        cd ../build2
        cmake --build . --config Release -j 4
    - name: build source
      run: |
        cd ../build2
        cmake --build . --config Release --target package_source || true
        mv generated_src out/
        cp ../robotraconteur/LICENSE.txt out/
    - name: test
      run: |
        cd ../build2
        ctest . -C Release --output-on-failure
    - name: move out
      run: |
        mv ../build2/out .
    - name: archive out
      uses: actions/upload-artifact@v2
      with:
        name: out
        path: out/*